# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class LiftoffExportCli < Formula
  desc "CLI tool to export and analyze workout data from the Liftoff fitness app"
  homepage "https://github.com/DTTerastar/liftoff-export-cli"
  version "1.0.3"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/DTTerastar/liftoff-export-cli/releases/download/v1.0.3/liftoff-export_darwin_amd64.zip"
      sha256 "268a562434cfca431255fc3187e38e8c986a628298b4b2e3a36d48896f0fabaa"

      define_method(:install) do
        bin.install "liftoff-export"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/DTTerastar/liftoff-export-cli/releases/download/v1.0.3/liftoff-export_darwin_arm64.zip"
      sha256 "b9b093553bf99df8e9d031d1f89897d4793a9d798777cf49e5610599d38cfa10"

      define_method(:install) do
        bin.install "liftoff-export"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/DTTerastar/liftoff-export-cli/releases/download/v1.0.3/liftoff-export_linux_amd64.zip"
      sha256 "2f44ec57da3c9d97adf9154f00d31fef422f2254160ef6e84320526355113f2f"
      define_method(:install) do
        bin.install "liftoff-export"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/DTTerastar/liftoff-export-cli/releases/download/v1.0.3/liftoff-export_linux_arm64.zip"
      sha256 "c829e183ee1b4d1d9a47ec8383596b271c480f4dd19840728276250415ce314e"
      define_method(:install) do
        bin.install "liftoff-export"
      end
    end
  end
end
