# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class LiftoffExport < Formula
  desc "CLI tool to export and analyze workout data from the Liftoff fitness app"
  homepage "https://github.com/DTTerastar/liftoff-export-cli"
  version "1.0.3"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/DTTerastar/liftoff-export-cli/releases/download/v1.0.3/liftoff-export_darwin_amd64.zip"
      sha256 "3348a3cca29caa7f872b3bbd5319b2df0f9028165c684cf68252f69f01beea17"

      define_method(:install) do
        bin.install "liftoff-export"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/DTTerastar/liftoff-export-cli/releases/download/v1.0.3/liftoff-export_darwin_arm64.zip"
      sha256 "266c058f90f0a217f211bbfc7e3caa7f7aebeb4fed052f8884f527a255efd33a"

      define_method(:install) do
        bin.install "liftoff-export"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/DTTerastar/liftoff-export-cli/releases/download/v1.0.3/liftoff-export_linux_amd64.zip"
      sha256 "c7815dee860889b312e3902eb0fea2319e49acfe5423674ff2214f8d86033d24"
      define_method(:install) do
        bin.install "liftoff-export"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/DTTerastar/liftoff-export-cli/releases/download/v1.0.3/liftoff-export_linux_arm64.zip"
      sha256 "96c8e51a7a2e7c5736191e98c2e8bb0205545e7a1d1f4a74f499a58ac0f4161f"
      define_method(:install) do
        bin.install "liftoff-export"
      end
    end
  end
end
