# This file was generated by GoReleaser. DO NOT EDIT.
cask "crono-export" do
  version "1.0.0"

  on_macos do
    on_intel do
      sha256 "51d399edba8cecdf603af0962d5c601bf6888a441f99f721e5df33a90c2b982b"
      url "https://github.com/quantcli/crono-export-cli/releases/download/v#{version}/crono-export_darwin_amd64.zip",
        verified: "github.com/quantcli/crono-export-cli"
    end
    on_arm do
      sha256 "391ad821f434b8e7965cac20ab2ac06b929a35c4be45c5f5fde902eb4b6e77a6"
      url "https://github.com/quantcli/crono-export-cli/releases/download/v#{version}/crono-export_darwin_arm64.zip",
        verified: "github.com/quantcli/crono-export-cli"
    end
  end

  on_linux do
    on_intel do
      sha256 "f35b17d85dec733f0b3ca450941418be24f863d60f35597305af30cee20b343a"
      url "https://github.com/quantcli/crono-export-cli/releases/download/v#{version}/crono-export_linux_amd64.zip",
        verified: "github.com/quantcli/crono-export-cli"
    end
    on_arm do
      sha256 "99d7d9b426c4fea8242aa7e63a9f3e79b41b46d2cfbe40de387bbc37aab09dff"
      url "https://github.com/quantcli/crono-export-cli/releases/download/v#{version}/crono-export_linux_arm64.zip",
        verified: "github.com/quantcli/crono-export-cli"
    end
  end

  name "crono-export"
  desc "CLI to export Cronometer nutrition, biometrics, and food log data as JSON"
  homepage "https://github.com/quantcli/crono-export-cli"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "crono-export"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/crono-export"]
    end
  end

  # No zap stanza required

end
