# This file was generated by GoReleaser. DO NOT EDIT.
cask "crono-export" do
  version "0.1.4"

  on_macos do
    on_intel do
      sha256 "37b4940e89774fc92e0f3a69f1f28a8092e3c42e4ea4350971a60ba576b0e258"
      url "https://github.com/quantcli/crono-export-cli/releases/download/v#{version}/crono-export_darwin_amd64.zip",
        verified: "github.com/quantcli/crono-export-cli"
    end
    on_arm do
      sha256 "e1b56633b7e9e4aaf7e81300fcfa146e0ebd9aa58f540b9ec205e3a54ce85f2e"
      url "https://github.com/quantcli/crono-export-cli/releases/download/v#{version}/crono-export_darwin_arm64.zip",
        verified: "github.com/quantcli/crono-export-cli"
    end
  end

  on_linux do
    on_intel do
      sha256 "59bff757fc9d3cdcde161f3190c477870d9d5049fcc2b17efb9e4d071aa33196"
      url "https://github.com/quantcli/crono-export-cli/releases/download/v#{version}/crono-export_linux_amd64.zip",
        verified: "github.com/quantcli/crono-export-cli"
    end
    on_arm do
      sha256 "9c9ad1a81661aad40f74fcece9376d43f2be2a650fe131efccc89f6f6d04b3c3"
      url "https://github.com/quantcli/crono-export-cli/releases/download/v#{version}/crono-export_linux_arm64.zip",
        verified: "github.com/quantcli/crono-export-cli"
    end
  end

  name "crono-export"
  desc "CLI to export Cronometer nutrition, biometrics, and food log data as JSON"
  homepage "https://github.com/quantcli/crono-export-cli"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "crono-export"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/crono-export"]
    end
  end

  # No zap stanza required

end
