# This file was generated by GoReleaser. DO NOT EDIT.
cask "liftoff-export" do
  version "1.3.0"

  on_macos do
    on_intel do
      sha256 "5121298af3b3cf6b24807b499d683d71fcfd7a8f830a27be358e25562e4f695a"
      url "https://github.com/quantcli/liftoff-export-cli/releases/download/v#{version}/liftoff-export_darwin_amd64.zip",
        verified: "github.com/quantcli/liftoff-export-cli"
    end
    on_arm do
      sha256 "9c3770b479e97e857fe4945a6fddade08101a61d96e68c81e2632d5dc194d8d1"
      url "https://github.com/quantcli/liftoff-export-cli/releases/download/v#{version}/liftoff-export_darwin_arm64.zip",
        verified: "github.com/quantcli/liftoff-export-cli"
    end
  end

  on_linux do
    on_intel do
      sha256 "f6c7fdd450944640577236ad68acc9f9ad095310430c0f9af35584e15bb48c7a"
      url "https://github.com/quantcli/liftoff-export-cli/releases/download/v#{version}/liftoff-export_linux_amd64.zip",
        verified: "github.com/quantcli/liftoff-export-cli"
    end
    on_arm do
      sha256 "0a5afbbf9faa2b1fb8a8ad8299e3fd4db5b3de5e70c8277c3fcc948690347106"
      url "https://github.com/quantcli/liftoff-export-cli/releases/download/v#{version}/liftoff-export_linux_arm64.zip",
        verified: "github.com/quantcli/liftoff-export-cli"
    end
  end

  name "liftoff-export"
  desc "CLI tool to export and analyze workout data from the Liftoff fitness app"
  homepage "https://github.com/quantcli/liftoff-export-cli"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "liftoff-export"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/liftoff-export"]
    end
  end

  # No zap stanza required

end
