# This file was generated by GoReleaser. DO NOT EDIT.
cask "liftoff-export" do
  version "1.3.1"

  on_macos do
    on_intel do
      sha256 "8e7e1829b399697b7316c5fa11801e3d06de6091063592e5e21aedd6fe5dcae7"
      url "https://github.com/quantcli/liftoff-export-cli/releases/download/v#{version}/liftoff-export_darwin_amd64.zip",
        verified: "github.com/quantcli/liftoff-export-cli"
    end
    on_arm do
      sha256 "257e764f30e976fa94ff54356f66d14cf66704ccbbc1696c1c4ee4c9f0620c74"
      url "https://github.com/quantcli/liftoff-export-cli/releases/download/v#{version}/liftoff-export_darwin_arm64.zip",
        verified: "github.com/quantcli/liftoff-export-cli"
    end
  end

  on_linux do
    on_intel do
      sha256 "535a7e0be7961df3dbdee75472060d8e7212e7641f66624a9e73cb7b84652107"
      url "https://github.com/quantcli/liftoff-export-cli/releases/download/v#{version}/liftoff-export_linux_amd64.zip",
        verified: "github.com/quantcli/liftoff-export-cli"
    end
    on_arm do
      sha256 "79b2cd0c704f6100900382a698e3641d50ad0c19e61b3c3f990bb73f2b696dfb"
      url "https://github.com/quantcli/liftoff-export-cli/releases/download/v#{version}/liftoff-export_linux_arm64.zip",
        verified: "github.com/quantcli/liftoff-export-cli"
    end
  end

  name "liftoff-export"
  desc "CLI tool to export and analyze workout data from the Liftoff fitness app"
  homepage "https://github.com/quantcli/liftoff-export-cli"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "liftoff-export"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/liftoff-export"]
    end
  end

  # No zap stanza required

end
