# This file was generated by GoReleaser. DO NOT EDIT.
cask "withings-export" do
  version "0.2.1"

  on_macos do
    on_intel do
      sha256 "6831b62ba8e5b3c9ba85d36027bb3ef8ecb6b6f61ca2ef43e6e2e4de008acdcc"
      url "https://github.com/quantcli/withings-export-cli/releases/download/v#{version}/withings-export_darwin_amd64.zip",
        verified: "github.com/quantcli/withings-export-cli"
    end
    on_arm do
      sha256 "8483a64bbbb4db7e9262623e7b7960ca0bd1f67f28be28d42069960c21669093"
      url "https://github.com/quantcli/withings-export-cli/releases/download/v#{version}/withings-export_darwin_arm64.zip",
        verified: "github.com/quantcli/withings-export-cli"
    end
  end

  on_linux do
    on_intel do
      sha256 "dc423af31c4b72d5b0cd9a5af14c2f8046b07d40cb1ec31ae8892ce1f87fd739"
      url "https://github.com/quantcli/withings-export-cli/releases/download/v#{version}/withings-export_linux_amd64.zip",
        verified: "github.com/quantcli/withings-export-cli"
    end
    on_arm do
      sha256 "48e36c79f7c8850e6d809b8d9f6ff3037b22ba07d42117c0fa7f2c3a633b8442"
      url "https://github.com/quantcli/withings-export-cli/releases/download/v#{version}/withings-export_linux_arm64.zip",
        verified: "github.com/quantcli/withings-export-cli"
    end
  end

  name "withings-export"
  desc "CLI to export health data from Withings (scales, watches, activity, sleep)"
  homepage "https://github.com/quantcli/withings-export-cli"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "withings-export"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/withings-export"]
    end
  end

  # No zap stanza required

end
