# This file was generated by GoReleaser. DO NOT EDIT.
cask "withings-export" do
  version "1.1.0"

  on_macos do
    on_intel do
      sha256 "35e757eb59a7be08036ee8784230e563da3eaa57ae2e480b890022251f4b8de0"
      url "https://github.com/quantcli/withings-export-cli/releases/download/v#{version}/withings-export_darwin_amd64.zip",
        verified: "github.com/quantcli/withings-export-cli"
    end
    on_arm do
      sha256 "41cff83d8d112f39ebb88a05d88f9ac7b2eb9213506e0be8a859c2db1ceb98dc"
      url "https://github.com/quantcli/withings-export-cli/releases/download/v#{version}/withings-export_darwin_arm64.zip",
        verified: "github.com/quantcli/withings-export-cli"
    end
  end

  on_linux do
    on_intel do
      sha256 "e9f48c1d5e45a43007d8ab15d22d82bcbcabcff3d4ab4e910326f85e0d704aee"
      url "https://github.com/quantcli/withings-export-cli/releases/download/v#{version}/withings-export_linux_amd64.zip",
        verified: "github.com/quantcli/withings-export-cli"
    end
    on_arm do
      sha256 "04fa49d25131425a4b851265d3b0cca9d6aa1f36f2f6458cfaf108972144186a"
      url "https://github.com/quantcli/withings-export-cli/releases/download/v#{version}/withings-export_linux_arm64.zip",
        verified: "github.com/quantcli/withings-export-cli"
    end
  end

  name "withings-export"
  desc "CLI to export health data from Withings (scales, watches, activity, sleep)"
  homepage "https://github.com/quantcli/withings-export-cli"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "withings-export"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/withings-export"]
    end
  end

  # No zap stanza required

end
