# This file was generated by GoReleaser. DO NOT EDIT.
cask "withings-export" do
  version "0.2.0"

  on_macos do
    on_intel do
      url "https://github.com/quantcli/withings-export-cli/releases/download/v#{version}/withings-export_darwin_amd64.zip",
        verified: "github.com/quantcli/withings-export-cli"
      sha256 "20f20498dd594926b9ee3e60a22492f0a37468e912351285c7c0d5ef651d548e"
    end
    on_arm do
      url "https://github.com/quantcli/withings-export-cli/releases/download/v#{version}/withings-export_darwin_arm64.zip",
        verified: "github.com/quantcli/withings-export-cli"
      sha256 "5c5cde3d5e5bea2fbbd48ac7628c381ce9a2ac741b4eb229036ea3ebb1c64350"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/quantcli/withings-export-cli/releases/download/v#{version}/withings-export_linux_amd64.zip",
        verified: "github.com/quantcli/withings-export-cli"
      sha256 "786af4fb56245ffebbcdbfd6bbd8a0bc2a92725392c3e501c77b0af3e378147a"
    end
    on_arm do
      url "https://github.com/quantcli/withings-export-cli/releases/download/v#{version}/withings-export_linux_arm64.zip",
        verified: "github.com/quantcli/withings-export-cli"
      sha256 "68be87d95c963c1bc02a730bb790945e523a9f89307f97fd371f03acbc21784b"
    end
  end

  name "withings-export"
  desc "CLI to export health data from Withings (scales, watches, activity, sleep)"
  homepage "https://github.com/quantcli/withings-export-cli"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "withings-export"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/withings-export"]
    end
  end

  # No zap stanza required

end
